### ISSUE TITLE
StreetView3DOverlay with OBJLoader

### ISSUE THREAD

**Issue by DimitrisGkikas** [rbejar/StreetView3DOverlay#1]
Hi Rubén,
Is it possible to use ObjLoader instead of jsonLoader? I am trying to replace the wheel with another 3d object and export it to JSON from Blender but it doesn't work.
Thank you

**Comment by rbejar** [comment]
I am afraid I haven't touched this code for years. If I find some time I'll try to make it work again, but I can't make any promises ;-)

**Comment by treeternity** [comment]
hi @rbejar - it looks like the code is not showing the ferris wheel anymore :(

http://rbejar.github.io/3DMappingExperiments/WebGLTests/StreetViewOverlay_EINA.html

do you think it is being blocked somehow?

**Comment by rbejar** [comment]
Hi @DimitrisGkikas, I have fixed the code. Now it loads the 3D object using the TDSLoader so it should be easy to modify it to use the ObjLoader with a different model.

**Comment by DimitrisGkikas** [comment]
Thank you so much @rbejar!

**Comment by DimitrisGkikas** [comment]
Hi @rbejar I am sorry for being annoying but the code stop working. It's weird because the [online example](https://www.rubenbejar.com/streetviewdemo/StreetView3DOverlay.html) works but the downloadable version no. Do you have any idea why? Thank you so much!

**Comment by rbejar** [comment]
Hi @DimitrisGkikas. Sorry it took me so long to look at this. If you clone the repository, double click on the file StreetView3DOverlay.html and see nothing on your browser, that is because the CORS mechanism. You could relax that security measure in your browser temporarily (how this is done depends on the browser). Another, better, alternative is launching a small web server for testing purposes. For instance, in my Kubuntu 18.04 (but this, or similar, should work anywhere you have Python installed), running `python -m SimpleHTTPServer` from a console on the same directory where you have cloned the git repository allows you to go to <http://localhost:8000/StreetView3DOverlay.html> from your browser and see the application working.

You will then see an ominous warning by Google telling you that their Maps API in that web page can only be used for development purposes. That is because I don't have an API key for production, and that is because it requires (I think) a credit card. And I do not see a reason to get one for this quick/simple demo.
